name: llm-eval-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas=2.2.2
  - numpy=1.26.4
  - scikit-learn=1.4.1
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - streamlit=1.35.0
  - jupyterlab=4.2.1
  - ipykernel=6.29.4
  - textblob=0.18.0
  - nltk=3.8.1
  - black=24.3.0
